language: go
sudo: false
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: 1.10.x
  - go: 1.11.x
script:
- go vet
- go test -v ./...
- if [ "${LATEST}" = "true" ]; then GOOS=linux GOARCH=amd64 go build -ldflags "-X
  main.Version=`git rev-parse --short HEAD`" -o goterra-store.linux.amd64 goterra-store.go;
  fi
- if [ "${LATEST}" = "true" ]; then GOOS=darwin GOARCH=amd64 go build -ldflags "-X
  main.Version=`git rev-parse --short HEAD`" -o goterra-store.darwin.amd64 goterra-store.go;
  fi
- if [ "${LATEST}" = "true" ]; then GOOS=windows GOARCH=amd64 go build -ldflags "-X
  main.Version=`git rev-parse --short HEAD`" -o goterra-store.windows.amd64.exe goterra-store.go;
  fi
- if [ "${LATEST}" = "true" ]; then GOOS=linux GOARCH=amd64 go build -ldflags "-X
  main.Version=`git rev-parse --short HEAD`" -o goterra-cli.linux.amd64 cmd/goterra-cli.go;
  fi
- if [ "${LATEST}" = "true" ]; then GOOS=darwin GOARCH=amd64 go build -ldflags "-X
  main.Version=`git rev-parse --short HEAD`" -o goterra-cli.darwin.amd64 cmd/goterra-cli.go;
  fi
- if [ "${LATEST}" = "true" ]; then GOOS=windows GOARCH=amd64 go build -ldflags "-X
  main.Version=`git rev-parse --short HEAD`" -o goterra-cli.windows.amd64.exe cmd/goterra-cli.go;
  fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KmXVtFYihhdd1kGV/l9kEiGV52Tu31vtyyuyynSW1n2svKP1kcKC2FqHkgyWorVlIJU3aTqzs+iuOpPZr4jGHGh4X3rF8QMA/WMtD+qLSAS+MmMNsMmso2P9UUeiSJIOqLG2mJgpzBUfDoRSrCY07b8jmrcO3scu++xpeITUSDNxjxECMU3qYtCsdufSJcoNCyQIm6UWEuBzjhvpqnw+CUJhM9236jfq4k3yU6mDhs8c1XFNIJo4N3e0nlIv2JVF9t2JQSnOxca93WXIay33BZbECt3ArAPyUjlYNMphFuhrJJh3rZR+tpKqDvQjiaLzhVijcv+sQ0U3GGuC6Qm3ZUb4pnodgxDXxSsXNiqKory479JaSUPxI8s36FgqkJD+KNpxkXM9hqFDrNn/MnkIBT+VL7GtaCNDajuJ73ZUShpxxfRkbv5lpVGvXArxkibtDbbaObMxASU7eTsEBCdrRC2LB8se3ZPaueWRareLun/tgH9BhMDiCk39p0tjVT4dzP+3zWcTYF33Ds3rCmzSKB4n0NEdTPNJIqrUSN/0MDANWyjkn7lf1T+YvL22UkWZDRXqXAINnQ+o1RxwdlLISqMio3GYSoyu9E+lmj2RXPzSp/L4F1XGZeIbAEL3Wy7kxuOaPvnXoXqBxXFICisRKtcDJLhCrTsaf3nqgGtGxNk=
  file:
          - goterra-store.linux.amd64
          - goterra-cli.linux.amd64
          - goterra-store.darwin.amd64
          - goterra-cli.darwin.amd64
          - goterra-store.windows.amd64.exe
          - goterra-cli.windows.amd64.exe
  on:
    repo: osallou/goterra-store
    tags: true
